theme: jekyll-theme-slate
title: Robot à Bonbons
description: A decorative robot that distributes candies during birthday parties.
show_downloads: false

github:
  owner_name: David de Lorenzo
  owner_url: https://sphinkie.github.io/